version: '3.8'
services:
  db2:
    image: mysql/mysql-server:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: cooleomuseo
      MYSQL_DATABASE: ThisAndThat
      MYSQL_ROOT_HOST: '%'
    volumes:
      - tatdat2:/var/lib/mysql
    ports:
      - "23306:3306"
  phpmyadmin2:
    image: phpmyadmin/phpmyadmin:latest
    restart: always
    depends_on:
      - db2
    environment:
      PMA_HOST: db2
      PMA_USER: root
      PMA_PASSWORD: cooleomuseo
    ports:
      - "8082:80"
volumes:
  tatdat2: